seed : 2019
paths:
  preprocessing :
    make_patches:
      input : 'data/test/img'
      output : "data/test/img_patches"
    fuse_patches:
      input : "output/test/sample_folder"
      output : "output/test/sample_folder_fused"
  train:
    img : "data/train/img_patches"
    label : "data/train/label_patches"
    pretrained_weights : ""
  validation :
    img : "data/val/img_patches"
    label : "data/val/label_patches"
  test :
    img : 'data/test/img_patches'
    label : 'data/test/label_patches'
    use_label : False
    pretrained_weights : "output/training/example_training/best.pt"
  output :
    training : "output/training/example_training"
    inference : 'output/test/example_training'
  
logic :
  device : "cuda"
  classes :
    - Background : 
      r : 0
      g : 0
      b : 0
    - Dough : 
      r : 255
      g : 128
      b : 128
    - Cheese : 
      r : 255
      g : 255
      b : 0
    - Mozzarella : 
      r : 255
      g : 255
      b : 255
    - Tomato Sauce : 
      r : 128
      g : 64
      b : 64
    - Prosciutto : 
      r : 255
      g : 0
      b : 0
  preprocessing :
    mode : "fuse"
    patch_size : 2056
    original_size :
      width : 4032
      height : 3024
  training :
    architecture : "deeplabv3_resnet50"
    pretrained : False
    freeze_weight : False
    data_aug :
      - "hflip"
      - "vflip"
    batch_size : 8
    lr : 0.001
    img_size : 512
    epochs : 300
    loss : 
      function : "CE"
      weights :
        Background : 1
        Dough : 1
        Cheese : 1
        Mozzarella : 1
        Tomato Sauce : 1
        Prosciutto : 1
    scheduler :
      use_schedule : False
      patience : 80
      factor : 0.8

  inference :
    quantization : 'fp16'
  visualization :
    show :
      train : 2
      validation : 2
      frequency : 10